# Default parameters for the pipeline

# level to read the image for core definition
IM_LEVEL: 6 

# parameters to refine rois
MIN_AREA: 2000
MAX_AREA: 10000
MIN_IOU: 0.8
MIN_ST: 0.9
MIN_INT: 15

# number of pixels to add to the bounding box of a roi
FRAME: 4

# Configuration for different workstations
workstations:
  
  ASB-1-1600-0035:
    model_path: ""
    sam2_env: ""

  DESKTOP-S71S74E:
    model_path: "/mnt/d/data_analysis/2024_bladder/sam2"
    sam_env: "/home/kasia/miniforge3/envs/sam2-env/bin/python"